version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: KOMPLEMON_app
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: KOMPLEMON_db
      DB_USERNAME: root
      DB_PASSWORD: root

  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: KOMPLEMON_db
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data: